name: ci-cd

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Instala/activa pnpm primero
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # 2) Ahora setup-node puede usar cache: pnpm sin romperse
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint || true

      - name: Test (coverage)
        run: pnpm test -- --coverage

      - name: Build (Next)
        run: pnpm build
